// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'album_image.freezed.dart';
// optional: Since our AlbumImage class is serializable, we must add this line.
// But if AlbumImage was not serializable, we could skip it.
part 'album_image.g.dart';

@freezed
class AlbumImage with _$AlbumImage {
  const factory AlbumImage({
    required bool back,
    required bool approved,
    required String comment,
    required bool front,
    required String id,
    required int edit,
    required String image,
    required Object thumbnails,
    required List types,
  }) = _AlbumImage;

  factory AlbumImage.fromJson(Map<String, Object?> json) =>
      _$AlbumImageFromJson(json);
}
