// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import 'artist.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'album_or_artist.freezed.dart';
// optional: Since our ReleaseGroup class is serializable, we must add this line.
// But if ReleaseGroup was not serializable, we could skip it.
part 'album_or_artist.g.dart';

@freezed
class AlbumOrArtist with _$AlbumOrArtist {
  const factory AlbumOrArtist({
    required String id,
    required String type,
    required String name,
    List<Artist>? artists,
    List? images,
  }) = _AlbumOrArtist;

  factory AlbumOrArtist.fromJson(Map<String, dynamic> json) =>
      _$AlbumOrArtistFromJson(json).copyWith(
        releaseDate: json['release_date'],
      );
}
