// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'release_group.freezed.dart';
// optional: Since our ReleaseGroup class is serializable, we must add this line.
// But if ReleaseGroup was not serializable, we could skip it.
part 'release_group.g.dart';

@freezed
class ReleaseGroup with _$ReleaseGroup {
  const factory ReleaseGroup({
    required List secondaryTypes,
    required String primaryTypeId,
    required String id,
    required String primaryType,
    required String disambiguation,
    required List secondaryTypeIds,
    required String firstReleaseDate,
    required String title,
  }) = _ReleaseGroup;

  factory ReleaseGroup.fromJson(Map<String, Object?> json) =>
      _$ReleaseGroupFromJson(json);
}
