// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'release_group_model.freezed.dart';
// optional: Since our ReleaseGroupModel class is serializable, we must add this line.
// But if ReleaseGroupModel was not serializable, we could skip it.
part 'release_group_model.g.dart';

@freezed
class ReleaseGroupModel with _$ReleaseGroupModel {
  const factory ReleaseGroupModel({
    required List secondaryTypes,
    required String primaryTypeId,
    required String id,
    required String primaryType,
    required String disambiguation,
    required List secondaryTypeIds,
    required String firstReleaseDate,
    required String title,
  }) = _ReleaseGroupModel;

  factory ReleaseGroupModel.fromJson(Map<String, Object?> json) =>
      _$ReleaseGroupModelFromJson(json);
}
