// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB-aLrJ1Qxsjde4haGfKRIUFZ7k_XyXVc',
    appId: '1:77492506614:web:d05a7e38e0b3f48eddc1d7',
    messagingSenderId: '77492506614',
    projectId: 'jdmiiim',
    authDomain: 'jdmiiim.firebaseapp.com',
    storageBucket: 'jdmiiim.appspot.com',
    measurementId: 'G-V3SJ00ECNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtl5D3imkTdAcglzLiRvg2Ohsf82DuyLg',
    appId: '1:77492506614:android:b78a1560fbbf004cddc1d7',
    messagingSenderId: '77492506614',
    projectId: 'jdmiiim',
    storageBucket: 'jdmiiim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSEFwUCMgh5_ri6OGF1jxqka046Xfn1fA',
    appId: '1:77492506614:ios:0bbc4a5ee5c38c30ddc1d7',
    messagingSenderId: '77492506614',
    projectId: 'jdmiiim',
    storageBucket: 'jdmiiim.appspot.com',
    iosBundleId: 'com.jdmiiim.Jamtrackd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSEFwUCMgh5_ri6OGF1jxqka046Xfn1fA',
    appId: '1:77492506614:ios:0bbc4a5ee5c38c30ddc1d7',
    messagingSenderId: '77492506614',
    projectId: 'jdmiiim',
    storageBucket: 'jdmiiim.appspot.com',
    iosBundleId: 'com.jdmiiim.Jamtrackd',
  );
}
